name: deployment_manager
description: A deployment manager with the task to find the best work schedule for everyone.
version: 0.1.0
# homepage: https://www.example.com
author: Benjamin Eder <barny.eder@gmail.com>

environment:
  sdk: '>=2.0.0 <3.0.0'

dependencies:
  angular: ^5.0.0
  angular_components: ^0.9.0

dev_dependencies:
  angular_test: ^2.0.0
  build_runner: ^0.10.0
  build_test: ^0.10.2
  build_web_compilers: ^0.4.0
  test: ^1.0.0
  sass_builder: ^2.1.1
